---
description: 
pack: aws_s3
enabled: true
entry_point: run.py
name: get_bucket_analytics_configuration
runner_type: python-script
parameters:
  action:
    default: get_bucket_analytics_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "The name of the bucket from which an analytics configuration is retrieved."
    required: true
  Id:
    type: string
    description: "The identifier used to represent an analytics configuration."
    required: true