---
description: 
pack: aws_s3
enabled: true
entry_point: run.py
name: list_bucket_analytics_configurations
runner_type: python-script
parameters:
  action:
    default: list_bucket_analytics_configurations
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "The name of the bucket from which analytics configurations are retrieved."
    required: true
  ContinuationToken:
    type: string
    description: "The ContinuationToken that represents a placeholder from where this request should begin."