---
description: 
pack: aws_s3
enabled: true
entry_point: run.py
name: put_bucket_analytics_configuration
runner_type: python-script
parameters:
  action:
    default: put_bucket_analytics_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "The name of the bucket to which an analytics configuration is stored."
    required: true
  Id:
    type: string
    description: "The identifier used to represent an analytics configuration."
    required: true
  AnalyticsConfiguration:
    type: object
    description: "The configuration and any analyses for the analytics filter."
    required: true